/** main.js v9.1 — Universal DSL + 新增插件注册 */
(function(){var A=window.AGE;A.PluginManager={_list:[],register:function(p){this._list.push(p);},get:function(n){for(var i=0;i<this._list.length;i++)if(this._list[i].name===n)return this._list[i];return null;}};A.PluginManager.register(A.RunnerPlugin);A.PluginManager.register(A.ShooterPlugin);A.PluginManager.register(A.PlatformPlugin);A.PluginManager.register(A.DungeonPlugin);A.PluginManager.register(A.StoryPlugin);
var cv=document.getElementById('game'),pi=document.getElementById('prompt'),eng=new A.GameEngine(cv);A._currentEngine=eng;
var inp=new A.InputManager({canvas:cv,onChargeStart:function(){var s=A.getGameState();if(s===A.STATE.GAMEOVER||s===A.STATE.WIN||eng.gameOver||eng._win){eng.restart();return;}eng.startCharge();},onChargeRelease:function(){var s=A.getGameState();if(s===A.STATE.GAMEOVER||s===A.STATE.WIN||eng.gameOver||eng._win)return;eng.releaseJump();},onChargeCancel:function(){eng.cancelCharge();},onAllKey:function(k){var s=A.getGameState();if(s===A.STATE.GAMEOVER||s===A.STATE.WIN||eng.gameOver||eng._win)return;if(eng.plugin&&eng.plugin.onAllKeys)eng.plugin.onAllKeys(eng,k);if(k!==' '&&eng.plugin&&eng.plugin.onPluginKey)eng.plugin.onPluginKey(eng,k);}});inp.bind();

window.generateGame=async function(){var prompt=pi.value.trim();if(!prompt){A.setStatus('请输入描述','error');return;}A.setGameState(A.STATE.LOADING);A.setStatus('AI生成中...','');var raw=await A.callAI(prompt);if(!raw){A.setGameState(A.STATE.IDLE);return;}var dsl=A.DSLBinder.bind(raw,prompt);var gt=((dsl.meta||{}).game_type||'runner');var plugin=A.PluginSelector.select(gt,A.PluginManager);eng.playTester=null;eng.load(dsl,plugin);A.setGameState(A.STATE.RUNNING);A.setStatus('['+gt+'] '+((dsl.meta||{}).title||'准备完成'),'success');updateHint();};

window.runAITest=function(){if(!eng.dsl||!eng.plugin){A.setStatus('请先生成或选择一个游戏','error');return;}A.setGameState(A.STATE.RUNNING);eng.playTester=new A.PlayTestSystem(eng);eng.playTester.start();A.setStatus('AI试玩运行中...','');(function poll(){if(!eng.playTester||eng.playTester._done||eng.gameOver||eng._win||eng.playTester.frame>=eng.playTester.maxFrames){if(eng.playTester)eng.playTester.stop();var report=eng.playTester?eng.playTester.generateReport():{status:'?',enemiesKilled:0,totalDamage:0,bossDamage:0};A.setStatus('结果:'+report.status+' 杀敌:'+report.enemiesKilled+' Boss伤:'+report.bossDamage+' 生存:'+report.survivalTime+'s','success');}else setTimeout(poll,100);})();};

window.generateAndTest=async function(){var prompt=pi.value.trim();if(!prompt){A.setStatus('请输入描述','error');return;}A.setGameState(A.STATE.LOADING);A.setStatus('AI生成中...','');var raw=await A.callAI(prompt);if(!raw){A.setGameState(A.STATE.IDLE);return;}var dsl=A.DSLBinder.bind(raw,prompt);var gt=((dsl.meta||{}).game_type||'runner');var plugin=A.PluginSelector.select(gt,A.PluginManager);
  var bestDSL=dsl,bestScore=-1,bestRound=0,allReports=[],totalFixes=0;
  for(var round=0;round<3;round++){eng.playTester=null;eng.load(dsl,plugin);A.setGameState(A.STATE.RUNNING);var tester=new A.PlayTestSystem(eng);eng.playTester=tester;tester.start();var bugDet=new A.BugDetector(eng);bugDet.reset();A.setStatus('轮次'+(round+1)+'/3 测试+找Bug...','');
    await new Promise(function(resolve){var check=function(){if(bugDet)try{bugDet.update();}catch(x){}if(!tester._active||tester._done||eng.gameOver||eng._win||tester.frame>=tester.maxFrames){tester.stop();eng.playTester=null;resolve();}else setTimeout(check,80);};check();});
    var fixes=bugDet.generateFixes();if(!tester._report)tester.generateReport();var r=tester._report;allReports.push(r);var score=(r.bossDamage||0)+(r.enemiesKilled||0)*10-(r.deathCount||0)*50-(r.totalDamage||0)*2;var bugMsg='';if(fixes.length>0){bugMsg=' 发现Bug:'+fixes.length+'个';dsl=bugDet.applyToDSL(dsl,fixes);totalFixes+=fixes.length;}A.setStatus('轮'+(round+1)+': '+r.status+' Boss伤:'+r.bossDamage+bugMsg,'success');if(score>bestScore){bestScore=score;bestDSL=JSON.parse(JSON.stringify(dsl));bestRound=round+1;}if(r.status!=='通过')dsl=A.DSLFixer.fix(dsl,r);}
  eng.playTester=null;eng.load(bestDSL,plugin);A.setGameState(A.STATE.RUNNING);var finalMsg='最佳:轮'+bestRound+'['+gt+']';if(totalFixes>0)finalMsg+=' 修复Bug:'+totalFixes+'个';A.setStatus(finalMsg,'success');updateHint();};

window.generateWithDirector=async function(){var prompt=pi.value.trim();if(!prompt){A.setStatus('请输入描述','error');return;}A.setGameState(A.STATE.LOADING);var director=new A.GameDirector();director._statusCallback=function(msg,type){A.setStatus(msg,type||'');};var result=await director.runDirectorLoop(prompt);if(!result.success){A.setGameState(A.STATE.IDLE);A.setStatus('导演失败: '+(result.error||'未知错误'),'error');return;}var gt=result.gameType||'runner';var finalMsg='🧠 导演完成['+gt+'] | 评分:'+result.score+' | 优化'+result.totalOptimizations+'次';A.setStatus(finalMsg,'success');updateHint();};

window.loadPreset=function(t){var plugin=A.PluginManager.get(t);if(!plugin||!plugin.preset)return;var dsl=A.DSLBinder.bind(plugin.preset,'');eng.playTester=null;eng.load(dsl,plugin);A.setGameState(A.STATE.RUNNING);A.setStatus(plugin.label+'已加载','success');updateHint();};
function updateHint(){var el=document.getElementById('hint');if(!el)return;if(eng.plugin&&eng.plugin.getHint)el.textContent=eng.plugin.getHint();else el.textContent='空格=跳跃';}
function loop(){eng.update();eng.render();requestAnimationFrame(loop);}loop();})();
