/** RacingPlugin.js - lane racing with speed, laps and obstacles */
(function(){var A=window.AGE,T=A.PluginTools;
A.RacingPlugin={name:'racing',label:'竞速',ownsLoop:true,
preset:{meta:{game_type:'racing',title:'霓虹赛道'},player:{hp:10},rules:{win_condition:'finish_laps',win_value:3},world:{theme:'night_city'},racing:{laps:3,lap_distance:900,time_limit:60}},
onLoad:function(e,d){var c=d.racing||{},laps=c.laps||3,lapDistance=c.lap_distance||900;e._noDefaultSpawn=true;e.racing={lane:1,speed:0,maxSpeed:9,distance:0,lapDistance:lapDistance,total:laps*lapDistance,laps:laps,timer:(c.time_limit||60)*60,tick:0,obstacles:[],hits:0};},
onUpdate:function(e){var s=e.racing;s.tick++;s.timer--;s.speed=Math.max(0,s.speed-.006);s.distance+=s.speed*.55;if(s.tick%150===0)s.obstacles.push({lane:(Math.floor(s.tick/150)+1)%3,distance:s.distance+420});for(var i=0;i<s.obstacles.length;i++){var o=s.obstacles[i],delta=o.distance-s.distance;if(delta<18&&delta>-10&&o.lane===s.lane){s.speed=Math.max(1,s.speed*.35);s.hits++;o.hit=true;}}s.obstacles=s.obstacles.filter(function(o){return !o.hit&&o.distance>s.distance-40;});e.score=s.distance;if(s.distance>=s.total)T.win(e,'竞速完成');else if(s.timer<=0)T.fail(e,'比赛超时');},
onAllKeys:function(e,k){var s=e.racing;if(k==='arrowup'||k==='w')s.speed=Math.min(s.maxSpeed,s.speed+1.1);else if(k==='arrowdown'||k==='s')s.speed=Math.max(0,s.speed-1.5);else if(k==='arrowleft'||k==='a')s.lane=Math.max(0,s.lane-1);else if(k==='arrowright'||k==='d')s.lane=Math.min(2,s.lane+1);},onPluginKey:function(){},
aiStep:function(e){var s=e.racing,nearest=null;for(var i=0;i<s.obstacles.length;i++){var delta=s.obstacles[i].distance-s.distance;if(delta>0&&delta<150&&(!nearest||delta<nearest.delta))nearest={lane:s.obstacles[i].lane,delta:delta};}if(nearest&&nearest.lane===s.lane)s.lane=s.lane===0?1:s.lane===2?1:0;s.speed=Math.min(s.maxSpeed,s.speed+.8);},
onRender:function(e){var c=e.renderer.ctx,s=e.racing;T.background(c,'#171b2a','霓虹赛道','完成 '+s.laps+' 圈并避开路障');var roadX=205,roadW=390;c.fillStyle='#30333d';c.fillRect(roadX,58,roadW,305);for(var i=1;i<3;i++){c.strokeStyle='rgba(255,255,255,.3)';c.setLineDash([12,12]);c.beginPath();c.moveTo(roadX+i*130,58);c.lineTo(roadX+i*130,363);c.stroke();c.setLineDash([]);}for(var j=0;j<s.obstacles.length;j++){var o=s.obstacles[j],rel=(o.distance-s.distance)/420;if(rel<0||rel>1)continue;var oy=330-rel*260,ox=roadX+o.lane*130+46;c.fillStyle='#f2c14e';c.fillRect(ox,oy,38,18);}var carX=roadX+s.lane*130+43;c.fillStyle='#ef476f';c.fillRect(carX,310,44,34);c.fillStyle='#7dd3fc';c.fillRect(carX+8,314,28,10);var lap=Math.min(s.laps,Math.floor(s.distance/s.lapDistance)+1);T.text(c,'圈 '+lap+'/'+s.laps,28,86,'#fff',16);T.text(c,'速度 '+s.speed.toFixed(1),28,116,'#7dd3fc',14);T.text(c,'时间 '+Math.ceil(s.timer/60),28,146,'#f2c14e',14);T.text(c,'碰撞 '+s.hits,28,176,'#ff899b',13);T.bar(c,28,215,130,10,s.distance,s.total,'#4fd1a5','赛程');T.text(c,'↑加速 ↓刹车 ←→换道',400,389,'rgba(255,255,255,.72)',12,'center');},
getStatsText:function(e){var s=e.racing;return' 速度:'+s.speed.toFixed(1)+' 圈:'+Math.min(s.laps,Math.floor(s.distance/s.lapDistance)+1)+'/'+s.laps;},getHint:function(){return'↑=加速 ↓=刹车 ←→=换道';}};
})();
