/** TowerDefensePlugin.js - tower placement, waves and base defense */
(function(){var A=window.AGE,T=A.PluginTools;
A.TowerDefensePlugin={name:'tower_defense',label:'塔防',ownsLoop:true,
preset:{meta:{game_type:'tower_defense',title:'峡谷防线'},player:{hp:12},rules:{win_condition:'defend_waves',win_value:5},world:{theme:'canyon'},tower_defense:{waves:5,slots:6,starting_gold:45}},
onLoad:function(e,d){var c=d.tower_defense||{};e._noDefaultSpawn=true;e.towerDefense={wave:0,maxWaves:c.waves||5,gold:c.starting_gold||45,baseHP:12,selected:0,tick:0,spawnRemaining:0,slots:new Array(c.slots||6).fill(0),enemies:[]};},
_build:function(e){var s=e.towerDefense;if(s.slots[s.selected]===0&&s.gold>=15){s.gold-=15;s.slots[s.selected]=1;}},
_upgrade:function(e){var s=e.towerDefense,lv=s.slots[s.selected],cost=lv*18;if(lv>0&&lv<3&&s.gold>=cost){s.gold-=cost;s.slots[s.selected]++;}},
onUpdate:function(e){var s=e.towerDefense;s.tick++;if(s.tick%120===0)s.gold+=5;if(s.spawnRemaining===0&&s.enemies.length===0&&s.wave<s.maxWaves){s.wave++;s.spawnRemaining=2+s.wave;}if(s.spawnRemaining>0&&s.tick%45===0){s.enemies.push({progress:0,hp:3+s.wave,maxHp:3+s.wave,speed:.0025+s.wave*.00025});s.spawnRemaining--;}
  for(var i=0;i<s.enemies.length;i++)s.enemies[i].progress+=s.enemies[i].speed;
  if(s.tick%24===0)for(var ti=0;ti<s.slots.length;ti++){var lv=s.slots[ti];if(!lv)continue;var pos=(ti+.5)/s.slots.length,target=null;for(var ei=0;ei<s.enemies.length;ei++){var en=s.enemies[ei];if(Math.abs(en.progress-pos)<.24&&(target===null||en.progress>s.enemies[target].progress))target=ei;}if(target!==null)s.enemies[target].hp-=lv*2;}
  var alive=[];for(var j=0;j<s.enemies.length;j++){var enemy=s.enemies[j];if(enemy.hp<=0){s.gold+=4;e.score+=20;}else if(enemy.progress>=1){s.baseHP--;if(s.baseHP<=0)T.fail(e,'基地被攻破');}else alive.push(enemy);}s.enemies=alive;
  if(s.wave>=s.maxWaves&&s.spawnRemaining===0&&s.enemies.length===0)T.win(e,'全部波次防守成功');},
onAllKeys:function(e,k){var s=e.towerDefense;if(k==='arrowleft'||k==='a')s.selected=(s.selected+s.slots.length-1)%s.slots.length;else if(k==='arrowright'||k==='d')s.selected=(s.selected+1)%s.slots.length;else if(k===' '||k==='1')this._build(e);else if(k==='u'||k==='e'||k==='2')this._upgrade(e);},onPluginKey:function(){},
aiStep:function(e){var s=e.towerDefense;for(var i=0;i<s.slots.length;i++)if(s.slots[i]===0&&s.gold>=15){s.selected=i;this._build(e);return;}for(var j=0;j<s.slots.length;j++)if(s.slots[j]>0&&s.slots[j]<3&&s.gold>=s.slots[j]*18){s.selected=j;this._upgrade(e);return;}},
onRender:function(e){var c=e.renderer.ctx,s=e.towerDefense;T.background(c,'#20251c','峡谷防线','守住 '+s.maxWaves+' 波敌人');T.text(c,'波次 '+s.wave+'/'+s.maxWaves,520,30,'#fff',14);T.text(c,'金币 '+s.gold,640,30,'#f2c14e',14);T.text(c,'基地 '+s.baseHP,720,30,'#78d8ae',14);c.fillStyle='#8d7150';c.fillRect(70,205,660,24);for(var i=0;i<s.slots.length;i++){var x=95+i*112,lv=s.slots[i];c.strokeStyle=i===s.selected?'#ffe169':'rgba(255,255,255,.35)';c.lineWidth=i===s.selected?3:1;c.strokeRect(x-22,145,44,46);if(lv){c.fillStyle='#4e8f72';c.fillRect(x-16,155,32,36);c.fillStyle='#d8f3dc';c.fillRect(x-3,138,6,20);T.text(c,'Lv'+lv,x,252,'#fff',11,'center');}else T.text(c,'空位',x,174,'rgba(255,255,255,.45)',11,'center');}for(var j=0;j<s.enemies.length;j++){var en=s.enemies[j],ex=70+en.progress*660;c.fillStyle='#d95562';c.fillRect(ex-10,198,20,20);T.bar(c,ex-12,190,24,4,en.hp,en.maxHp,'#ff8f99');}T.text(c,'←→ 选择塔位 · 空格 建造(15) · U/E 升级',400,368,'rgba(255,255,255,.72)',12,'center');},
getStatsText:function(e){var s=e.towerDefense;return' 波:'+s.wave+'/'+s.maxWaves+' 基地:'+s.baseHP;},getHint:function(){return'←→=选择塔位 空格=建造 U/E=升级';}};
})();
