/** Engine.js v9.2 — story模式纯净渲染(无地面/无敌人/无粒子) */
(function(){var A=window.AGE,D=A.DEFAULTS;A.GameEngine=function(cv){this.canvas=cv;this.renderer=new A.Renderer(cv);this.player=new A.Player();this.enemyMgr=new A.EnemyManager();this.powerupMgr=new A.PowerupManager();this.particleSys=new A.ParticleSystem();this.physics=new A.Physics();this.trailSys=new A.TrailSystem();this.spawner=new A.Spawner(D.enemy,D.powerup);this.assetSystem=new A.AssetSystem();this.plugin=null;this.rules=null;this.skillSystem=null;this.bossSystem=null;this.levelMgr=null;this.mapSystem=null;this.playTester=null;this.dsl=null;this.frame=0;this.score=0;this.groundY=D.world.groundY;this.scrollSpeed=D.world.scrollSpeed;this.gameOver=false;this._win=false;this.powerupActive=null;this.powerupTimer=0;this.doubleJumpAvailable=false;this._noDefaultSpawn=false;this._projectiles=[];this._bossShield=null;this._aoeFlash=0;this._onBossDefeated=null;this.maxChargeTime=D.charge.maxChargeTime;this.chargeBar=document.getElementById('chargeBar');this.chargeFill=document.getElementById('chargeFill');this._gameType='';};
A.GameEngine.prototype.reset=function(){this.plugin=null;this.rules=null;this.skillSystem=null;this.bossSystem=null;this.levelMgr=null;this.mapSystem=null;this.playTester=null;this.dsl=null;this.frame=0;this.score=0;this.groundY=D.world.groundY;this.scrollSpeed=D.world.scrollSpeed;this.gameOver=false;this._win=false;this.powerupActive=null;this.powerupTimer=0;this.doubleJumpAvailable=false;this._noDefaultSpawn=false;this._projectiles=[];this._bossShield=null;this._aoeFlash=0;this._onBossDefeated=null;this.player.reset();this.enemyMgr.reset();this.powerupMgr.reset();this.particleSys.reset();this.trailSys.reset();this.assetSystem=new A.AssetSystem();this.physics.setGravity(D.world.gravity);this.physics.updatePlayer=A.Physics.prototype._origUpdatePlayer;this.spawner.setEnemyCfg(D.enemy);this.spawner.setPowerupCfg(D.powerup);this._hideChargeBar();this._gameType='';};
A.GameEngine.prototype.load=function(dsl,plugin){this.reset();this.dsl=dsl||{};this.plugin=plugin||null;this._gameType=((this.dsl.meta||{}).game_type||'');this._noDefaultSpawn=(this._gameType==='story');var p=this.dsl.player||{};this.player.reset({hp:p.hp,jumpPower:p.jump_power,speed:p.speed,size:p.size,maxJumpMultiplier:p.max_jump_multiplier,groundY:(this.dsl.world||{}).ground_y});var w=this.dsl.world||{};this.groundY=w.ground_y||D.world.groundY;this.scrollSpeed=w.scroll_speed||D.world.scrollSpeed;this.physics.setGravity(w.gravity);var e=(this.dsl.enemies||[])[0]||{};this.spawner.setEnemyCfg({speed:e.speed||D.enemy.speed,spawnRate:e.spawn_rate||D.enemy.spawnRate,size:Math.min(e.size||D.enemy.size,30),type:e.type||D.enemy.type,hp:(typeof e.hp==='number'&&e.hp>0)?e.hp:1});var pu=(this.dsl.powerups||[])[0]||{};this.spawner.setPowerupCfg({spawnRate:pu.spawn_rate||D.powerup.spawnRate,duration:pu.duration||D.powerup.duration,type:pu.type||D.powerup.type});this.rules=new A.Rules(this.dsl.rules||{});this.skillSystem=new A.SkillSystem(this.dsl);if(this.dsl.assets)this.assetSystem.load({assets:this.dsl.assets});if(this.plugin&&this.plugin.onLoad){try{this.plugin.onLoad(this,this.dsl);}catch(x){}}this.gameOver=false;this._win=false;this._hideChargeBar();};
A.GameEngine.prototype.startCharge=function(){if(this._gameType==='story')return;if(this.gameOver||this._win||A.getGameState()===A.STATE.GAMEOVER||A.getGameState()===A.STATE.WIN)return;if(this.player.startCharge())this._showChargeBar();};
A.GameEngine.prototype.releaseJump=function(){if(!this.player.isCharging)return;if(this.gameOver||this._win||A.getGameState()===A.STATE.GAMEOVER||A.getGameState()===A.STATE.WIN)return;var r=this.player.releaseJump(this.maxChargeTime);if(r){this._hideChargeBar();this.particleSys.spawnJump(this.player.x+this.player.w/2,this.player.y+this.player.h,r.chargeRatio);}};
A.GameEngine.prototype.cancelCharge=function(){this.player.cancelCharge();this._hideChargeBar();};
A.GameEngine.prototype.getState=function(){var em=this.enemyMgr.enemies.filter(function(x){return x.hp>0;});return{player:{hp:this.player.hp,x:this.player.x,y:this.player.y,jumping:this.player.isJumping},enemyCount:em.length,bossHP:this.bossSystem&&this.bossSystem.hp>0?this.bossSystem.hp:0,gameOver:this.gameOver,win:this._win,score:Math.floor(this.score)};};
A.GameEngine.prototype.update=function(){if(this._gameType==='story'){this.frame++;if(this.playTester&&this.playTester._active&&!this.playTester._done)this.playTester.update();if(this.plugin&&this.plugin.onUpdate)try{this.plugin.onUpdate(this);}catch(x){}A.updateStats(this);return;}if(this.gameOver||this._win||A.getGameState()===A.STATE.GAMEOVER||A.getGameState()===A.STATE.WIN)return;this.frame++;this.score+=0.05;if(this.playTester&&this.playTester._active&&!this.playTester._done)this.playTester.update();if(this._aoeFlash>0)this._aoeFlash--;this.player.updateCharge(this.maxChargeTime);if(this.player.isCharging&&this.chargeFill)this.chargeFill.style.width=(Math.min(this.player.chargeTime/this.maxChargeTime,1)*100)+'%';var landed=this.physics.updatePlayer(this.player,this.groundY);if(landed==='platform'){this.particleSys.spawnLand(this.player.x+this.player.w/2,this.player.y+this.player.h);this.doubleJumpAvailable=false;}else if(landed==='ground'){this.particleSys.spawnLand(this.player.x+this.player.w/2,this.groundY);}else if(landed==='fall_through'){this._triggerGameOver();return;}this.trailSys.update(this.player,this.frame);this.particleSys.update();if(!this._noDefaultSpawn){if(this.spawner.shouldSpawnEnemy(this.frame))this.enemyMgr.spawnGround(this.spawner.enemyCfg,this.groundY);if(this.spawner.shouldSpawnPowerup(this.frame))this.powerupMgr.spawn(this.spawner.powerupCfg,this.groundY);}this.enemyMgr.update();this.powerupMgr.update();for(var ei=0;ei<this.enemyMgr.enemies.length;ei++){var enemy=this.enemyMgr.enemies[ei];if(enemy.hp>0&&A.hit(this.player,enemy)){if(this.powerupActive==='shield'){this.powerupActive=null;this.powerupTimer=0;this.particleSys.spawnShieldBreak(this.player.x+this.player.w/2,this.player.y+this.player.h/2);}else{this.player.hp-=1;this.particleSys.spawnHit(this.player.x+this.player.w/2,this.player.y+this.player.h/2,0);if(this.player.hp<=0){this._triggerGameOver();return;}}enemy.hp=0;}}if(this.bossSystem&&this.bossSystem.hp>0){try{this.bossSystem.update(this);}catch(x){}}if(this.skillSystem)this.skillSystem.update(this);if(this.plugin&&this.plugin.onUpdate){try{this.plugin.onUpdate(this);}catch(x){}}for(var pui=0;pui<this.powerupMgr.powerups.length;pui++){var puObj=this.powerupMgr.powerups[pui];if(puObj.hp!==0&&A.hit(this.player,puObj)){var puType=puObj.type||'speed';if(puType==='double')this.doubleJumpAvailable=true;else{this.powerupActive=puType;this.powerupTimer=this.spawner.powerupCfg.duration||120;}this.particleSys.spawnCollect(puObj.x+puObj.w/2,puObj.y+puObj.h/2);puObj.hp=0;}}if(this.powerupActive){this.powerupTimer--;if(this.powerupTimer<=0)this.powerupActive=null;}if(this.rules){var result=this.rules.evaluate(this);if(result==='win'){this._win=true;A.setGameState(A.STATE.WIN);}else if(result==='fail'){this._triggerGameOver();return;}}A.updateStats(this);};
A.GameEngine.prototype.render=function(){
  // ★ story模式: 纯净渲染(plugin.onRender 负责全部画面)
  if(this._gameType==='story'){this.renderer.clear();if(this.plugin&&this.plugin.onRender)try{this.plugin.onRender(this);}catch(x){}return;}
  this.renderer.clear();this.renderer.renderBackground();this.renderer.renderGround(this.groundY);this.trailSys.render(this.renderer.ctx,this.player.w,this.player.h);
  if(this.mapSystem)try{this.mapSystem.render(this.renderer.ctx,this);}catch(x){}
  this.particleSys.render(this.renderer.ctx);this.powerupMgr.render(this.renderer.ctx);
  for(var i=0;i<this.enemyMgr.enemies.length;i++){var en=this.enemyMgr.enemies[i];if(en.hp<=0)continue;var enAsset='enemy';if(en.type==='summon')enAsset='summon';try{this.assetSystem.renderCharacter(this.renderer.ctx,enAsset,en.x,en.y,en.w,en.h,this.frame);}catch(xx){}try{this.assetSystem.renderWeapon(this.renderer.ctx,'staff',en.x+en.w-2,en.y+en.h/2);}catch(xx){}var ctx=this.renderer.ctx;ctx.fillStyle='rgba(0,0,0,0.5)';ctx.fillRect(en.x,en.y-6,en.w,4);ctx.fillStyle='#0f0';ctx.fillRect(en.x,en.y-6,en.w*(en.hp/(en.maxHp||2)),4);}
  if(this.plugin&&this.plugin.onRender){try{this.plugin.onRender(this);}catch(x){}}var pn=this.plugin?this.plugin.name||'':'';if(this.skillSystem)this.skillSystem.render(this.renderer.ctx,pn);
  if(this._projectiles&&this._projectiles.length){var ctx=this.renderer.ctx;for(var i=0;i<this._projectiles.length;i++){var pp=this._projectiles[i];if(pp.hp<=0)continue;ctx.shadowColor=pp.glowColor||'#ff6600';ctx.shadowBlur=20;ctx.fillStyle=pp.color||'#ff8800';ctx.fillRect(pp.x,pp.y,pp.w,pp.h);ctx.shadowBlur=0;ctx.fillStyle=pp.innerColor||'#ffff00';ctx.fillRect(pp.x+3,pp.y+3,pp.w-6,pp.h-6);}}
  if(this._aoeFlash>0&&this._aoeFlash%2===0){this.renderer.ctx.fillStyle='rgba(255,0,0,0.15)';this.renderer.ctx.fillRect(0,0,800,400);}
  try{this.assetSystem.renderCharacter(this.renderer.ctx,'player',this.player.x,this.player.y,this.player.w,this.player.h,this.frame);}catch(xx){this.renderer.renderPlayer(this.player,this.frame,this.powerupActive);}
  this.renderer.renderUI(this);
  if(this.gameOver||A.getGameState()===A.STATE.GAMEOVER)this.renderer.renderEndScreen(this.score,false);if(this._win||A.getGameState()===A.STATE.WIN)this.renderer.renderEndScreen(this.score,true);};
A.GameEngine.prototype.restart=function(){if(this.dsl){this.load(this.dsl,this.plugin);A.setGameState(A.STATE.RUNNING);}else{this.reset();A.setGameState(A.STATE.IDLE);}};
A.GameEngine.prototype._triggerGameOver=function(){if(this._gameType==='story')return;this.gameOver=true;A.setGameState(A.STATE.GAMEOVER);this.particleSys.spawnDeath(this.player.x+this.player.w/2,this.player.y+this.player.h/2);};
A.GameEngine.prototype._showChargeBar=function(){if(this.chargeBar)this.chargeBar.style.display='block';if(this.chargeFill)this.chargeFill.style.width='0%';};A.GameEngine.prototype._hideChargeBar=function(){if(this.chargeBar)this.chargeBar.style.display='none';if(this.chargeFill)this.chargeFill.style.width='0%';};
})();

/** Full-loop plugins for board, card, management and racing games. */
(function(){var A=window.AGE;
var baseUpdate=A.GameEngine.prototype.update;
var baseRender=A.GameEngine.prototype.render;
var baseStartCharge=A.GameEngine.prototype.startCharge;
A.GameEngine.prototype.update=function(){
  if(!(this.plugin&&this.plugin.ownsLoop))return baseUpdate.call(this);
  if(this.gameOver||this._win||A.getGameState()===A.STATE.GAMEOVER||A.getGameState()===A.STATE.WIN)return;
  this.frame++;this.score+=0.05;
  if(this.playTester&&this.playTester._active&&!this.playTester._done)this.playTester.update();
  if(this.plugin.onUpdate)try{this.plugin.onUpdate(this);}catch(x){console.error(x);}
  A.updateStats(this);
};
A.GameEngine.prototype.render=function(){
  if(!(this.plugin&&this.plugin.ownsLoop))return baseRender.call(this);
  this.renderer.clear();
  if(this.plugin.onRender)try{this.plugin.onRender(this);}catch(x){console.error(x);}
  if(this.gameOver||A.getGameState()===A.STATE.GAMEOVER)this.renderer.renderEndScreen(this.score,false);
  if(this._win||A.getGameState()===A.STATE.WIN)this.renderer.renderEndScreen(this.score,true);
};
A.GameEngine.prototype.startCharge=function(){
  if(this.plugin&&this.plugin.ownsLoop)return;
  return baseStartCharge.call(this);
};
})();
