/** CardPlugin.js - deck, energy and turn combat */
(function(){var A=window.AGE,T=A.PluginTools;
var CARDS=[{name:'重击',cost:2,type:'attack',value:9,color:'#d85b68'},{name:'快斩',cost:1,type:'attack',value:5,color:'#e28a47'},{name:'格挡',cost:1,type:'block',value:6,color:'#4f8ec9'},{name:'治疗',cost:2,type:'heal',value:5,color:'#55a878'},{name:'蓄势',cost:0,type:'block',value:3,color:'#8b75ba'}];
A.CardPlugin={name:'card',label:'卡牌对战',ownsLoop:true,
preset:{meta:{game_type:'card',title:'符文牌局'},player:{hp:18},rules:{win_condition:'enemy_defeated',win_value:1},world:{theme:'arcane'},card:{enemy_hp:42,hand_size:5,energy:3}},
onLoad:function(e,d){var c=d.card||{};e._noDefaultSpawn=true;e.card={turn:1,energy:c.energy||3,maxEnergy:c.energy||3,block:0,enemyHP:c.enemy_hp||42,enemyMax:c.enemy_hp||42,enemyAttack:6,drawIndex:0,hand:[]};e.player.hp=Math.max(e.player.hp||0,18);e.player.maxHp=e.player.hp;for(var i=0;i<(c.hand_size||5);i++)this._draw(e);},
_draw:function(e){var s=e.card,base=CARDS[s.drawIndex%CARDS.length];s.hand.push({name:base.name,cost:base.cost,type:base.type,value:base.value,color:base.color});s.drawIndex++;},
_play:function(e,index){var s=e.card,card=s.hand[index];if(!card||card.cost>s.energy)return false;s.energy-=card.cost;if(card.type==='attack'){s.enemyHP-=card.value;e.score+=card.value*5;}else if(card.type==='block')s.block+=card.value;else if(card.type==='heal')e.player.hp=Math.min(e.player.maxHp,e.player.hp+card.value);s.hand.splice(index,1);this._draw(e);return true;},
_endTurn:function(e){var s=e.card,damage=Math.max(0,s.enemyAttack-s.block);e.player.hp-=damage;s.block=0;s.turn++;s.energy=s.maxEnergy;if(s.turn%3===0)s.enemyAttack++;while(s.hand.length<5)this._draw(e);},
onUpdate:function(e){if(e.card.enemyHP<=0)T.win(e,'牌局胜利');else if(e.player.hp<=0)T.fail(e,'牌局失败');},
onAllKeys:function(e,k){var n=parseInt(k,10);if(n>=1&&n<=5)this._play(e,n-1);else if(k==='enter'||k===' ')this._endTurn(e);},onPluginKey:function(){},
aiStep:function(e){var s=e.card,best=-1;for(var i=0;i<s.hand.length;i++)if(s.hand[i].cost<=s.energy&&s.hand[i].type==='attack'&&(best<0||s.hand[i].value>s.hand[best].value))best=i;if(best<0)for(var j=0;j<s.hand.length;j++)if(s.hand[j].cost<=s.energy&&(s.hand[j].type==='block'||s.hand[j].type==='heal')){best=j;break;}if(best>=0)this._play(e,best);else this._endTurn(e);},
onRender:function(e){var c=e.renderer.ctx,s=e.card;T.background(c,'#211b2b','符文牌局','用能量组合手牌击败守门人');T.text(c,'回合 '+s.turn,24,62,'rgba(255,255,255,.7)',12);T.bar(c,70,90,250,14,e.player.hp,e.player.maxHp,'#58b07c','玩家生命 '+e.player.hp+'/'+e.player.maxHp+'  护甲 '+s.block);T.bar(c,480,90,250,14,s.enemyHP,s.enemyMax,'#d95767','敌人生命 '+Math.max(0,s.enemyHP)+'/'+s.enemyMax+'  下回合伤害 '+s.enemyAttack);T.text(c,'能量 '+s.energy+'/'+s.maxEnergy,400,140,'#f4d35e',17,'center');for(var i=0;i<s.hand.length;i++){var card=s.hand[i],x=55+i*145;T.panel(c,x,175,125,145);c.fillStyle=card.color;c.fillRect(x,175,125,8);T.text(c,(i+1)+'. '+card.name,x+12,207,'#fff',14);T.text(c,'消耗 '+card.cost,x+12,235,'#f4d35e',12);T.text(c,card.type==='attack'?'伤害 '+card.value:card.type==='block'?'护甲 '+card.value:'恢复 '+card.value,x+12,273,'rgba(255,255,255,.78)',12);}T.text(c,'数字键 1-5 出牌 · Enter/空格 结束回合',400,372,'rgba(255,255,255,.72)',12,'center');},
getStatsText:function(e){return' 回合:'+e.card.turn+' 敌:'+Math.max(0,e.card.enemyHP);},getHint:function(){return'1-5=出牌 Enter/空格=结束回合';}};
})();
