/** SimulationPlugin.js - compact city management loop */
(function(){var A=window.AGE,T=A.PluginTools;
A.SimulationPlugin={name:'simulation',label:'模拟经营',ownsLoop:true,
preset:{meta:{game_type:'simulation',title:'河谷小镇'},player:{hp:10},rules:{win_condition:'population_goal',win_value:80},world:{theme:'river_town'},simulation:{target_population:80,starting_gold:65}},
onLoad:function(e,d){var c=d.simulation||{};e._noDefaultSpawn=true;e.simulation={day:1,gold:c.starting_gold||65,food:35,population:20,target:c.target_population||80,happiness:65,capacity:40,farms:1,houses:1,workshops:0,tick:0};},
_buildFarm:function(e){var s=e.simulation;if(s.gold>=20){s.gold-=20;s.farms++;}},_buildHouse:function(e){var s=e.simulation;if(s.gold>=25){s.gold-=25;s.houses++;s.capacity+=20;}},_buildWorkshop:function(e){var s=e.simulation;if(s.gold>=35){s.gold-=35;s.workshops++;}},
_advance:function(e){var s=e.simulation;s.day++;s.gold+=6+s.workshops*9;s.food+=s.farms*10-Math.ceil(s.population/5);if(s.food<0){s.population=Math.max(0,s.population-4);s.happiness-=8;}else if(s.population<s.capacity&&s.food>s.population/3){s.population+=2+s.houses;s.happiness=Math.min(100,s.happiness+1);}s.happiness=T.clamp(s.happiness,0,100);if(s.population<=0||s.happiness<=0)T.fail(e,'小镇失去活力');if(s.population>=s.target&&s.happiness>=60)T.win(e,'小镇繁荣目标达成');},
onUpdate:function(e){var s=e.simulation;s.tick++;if(s.tick%90===0)this._advance(e);},
onAllKeys:function(e,k){if(k==='1'||k==='f')this._buildFarm(e);else if(k==='2'||k==='h')this._buildHouse(e);else if(k==='3'||k==='w')this._buildWorkshop(e);else if(k===' '||k==='enter')this._advance(e);},onPluginKey:function(){},
aiStep:function(e){var s=e.simulation;if(s.food<s.population/2&&s.gold>=20)this._buildFarm(e);else if(s.population+10>=s.capacity&&s.gold>=25)this._buildHouse(e);else if(s.gold>=35)this._buildWorkshop(e);if(s.tick%30===0)this._advance(e);},
onRender:function(e){var c=e.renderer.ctx,s=e.simulation;T.background(c,'#193133','河谷小镇','人口达到 '+s.target+' 且幸福度不低于 60');T.text(c,'第 '+s.day+' 天',690,30,'#fff',14);var stats=[['人口',s.population+'/'+s.target,'#75d5b0'],['金币',s.gold,'#f2c14e'],['食物',s.food,'#e59b5b'],['幸福',s.happiness,'#e78da7']];for(var i=0;i<4;i++){var x=35+i*190;T.panel(c,x,75,160,65);T.text(c,stats[i][0],x+14,99,'rgba(255,255,255,.6)',11);T.text(c,String(stats[i][1]),x+14,126,stats[i][2],20);}var buildings=[['农场',s.farms,'1 / F','+食物'],['住宅',s.houses,'2 / H','+容量'],['工坊',s.workshops,'3 / W','+金币']];for(var j=0;j<3;j++){var bx=70+j*245;T.panel(c,bx,180,205,135);T.text(c,buildings[j][0],bx+18,212,'#fff',17);T.text(c,'数量 '+buildings[j][1],bx+18,244,'#6ee7b7',14);T.text(c,buildings[j][3],bx+18,273,'rgba(255,255,255,.62)',12);T.text(c,buildings[j][2],bx+160,298,'#f2c14e',11,'center');}T.text(c,'1 农场 · 2 住宅 · 3 工坊 · 空格 推进一天',400,370,'rgba(255,255,255,.72)',12,'center');},
getStatsText:function(e){var s=e.simulation;return' 人口:'+s.population+' 食物:'+s.food;},getHint:function(){return'1=农场 2=住宅 3=工坊 空格=推进';}};
})();
