/** StrategyPlugin.js - lane control and resource decisions */
(function(){var A=window.AGE,T=A.PluginTools;
A.StrategyPlugin={name:'strategy',label:'即时策略',ownsLoop:true,
preset:{meta:{game_type:'strategy',title:'三线远征'},player:{hp:10},rules:{win_condition:'conquest',win_value:3},world:{theme:'war_map'},strategy:{starting_gold:30,lane_strength:6}},
onLoad:function(e,d){var c=d.strategy||{},enemy=c.lane_strength||6;e._noDefaultSpawn=true;e.strategy={gold:c.starting_gold||30,income:4,baseHP:10,selected:0,tick:0,lanes:[{name:'北线',player:0,enemy:enemy},{name:'中线',player:0,enemy:enemy+2},{name:'南线',player:0,enemy:enemy}]};},
_deploy:function(e){var s=e.strategy,l=s.lanes[s.selected];if(s.gold>=10){s.gold-=10;l.player+=3;}},
_attack:function(e){var s=e.strategy,l=s.lanes[s.selected];if(l.player<=0||l.enemy<=0)return;var hit=Math.min(2,l.player);l.enemy=Math.max(0,l.enemy-hit);if(l.enemy>0&&Math.random()<.35)l.player=Math.max(0,l.player-1);e.score+=hit*10;},
onUpdate:function(e){var s=e.strategy;s.tick++;if(s.tick%90===0)s.gold+=s.income;if(s.tick%210===0){for(var i=0;i<s.lanes.length;i++){var l=s.lanes[i];if(l.enemy>0){if(l.player>0)l.player=Math.max(0,l.player-1);else s.baseHP--;}}if(s.baseHP<=0)T.fail(e,'指挥部失守');}var won=true;for(var j=0;j<s.lanes.length;j++)if(s.lanes[j].enemy>0)won=false;if(won)T.win(e,'三条战线全部占领');},
onAllKeys:function(e,k){var s=e.strategy;if(k==='arrowup'||k==='w')s.selected=(s.selected+2)%3;else if(k==='arrowdown'||k==='s')s.selected=(s.selected+1)%3;else if(k===' '||k==='1')this._deploy(e);else if(k==='j'||k==='enter'||k==='2')this._attack(e);},onPluginKey:function(){},
aiStep:function(e){var s=e.strategy,best=0;for(var i=1;i<3;i++)if(s.lanes[i].enemy<s.lanes[best].enemy&&s.lanes[i].enemy>0)best=i;if(s.lanes[best].enemy<=0)for(var j=0;j<3;j++)if(s.lanes[j].enemy>0){best=j;break;}s.selected=best;if(s.gold>=10)this._deploy(e);this._attack(e);},
onRender:function(e){var c=e.renderer.ctx,s=e.strategy;T.background(c,'#1e252b','三线远征','分配军力并击破全部防线');T.text(c,'军费 '+s.gold,610,30,'#f2c14e',14);T.text(c,'基地 '+s.baseHP,700,30,'#7ee0b8',14);for(var i=0;i<3;i++){var y=82+i*96,l=s.lanes[i];T.panel(c,32,y,736,76);if(i===s.selected){c.strokeStyle='#f2c14e';c.lineWidth=3;c.strokeRect(32,y,736,76);}T.text(c,l.name,52,y+30,'#fff',16);T.text(c,'我方 '+l.player,190,y+30,'#68b7ff',14);T.text(c,'敌方 '+l.enemy,620,y+30,l.enemy>0?'#ff7588':'#70d6a5',14);T.bar(c,190,y+47,200,9,l.player,12,'#3f8fd1');T.bar(c,418,y+47,200,9,l.enemy,10,'#cf4b5d');if(l.enemy<=0)T.text(c,'已占领',688,y+48,'#70d6a5',13,'center');}T.text(c,'↑↓ 选择战线 · 空格 部署(10军费) · J/Enter 进攻',400,382,'rgba(255,255,255,.72)',12,'center');},
getStatsText:function(e){return' 军费:'+e.strategy.gold+' 基地:'+e.strategy.baseHP;},getHint:function(){return'↑↓=选择战线 空格=部署 J/Enter=进攻';}};
})();
